FROM php:8-apache

# PHPにて必要なライブラリをインストール
RUN apt-get update && apt-get install -y libonig-dev libzip-dev unzip && docker-php-ext-install mbstring zip bcmath && docker-php-ext-install pdo_mysql && pecl install xdebug && docker-php-ext-enable xdebug

#composer のインストール
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1

# ファイルのコピー
COPY ./src /var/www/html
COPY ./docker/app/php.ini /usr/local/etc/php/php.ini
COPY ./docker/app/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
